# Generated by Django 3.2.12 on 2022-05-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25, verbose_name='Id пользователя')),
                ('username', models.CharField(max_length=255, verbose_name='Ник пользователя')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('date_registered', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='TradeInDevicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название кнопки')),
            ],
            options={
                'verbose_name': 'Главные кнопки',
                'verbose_name_plural': 'Главные кнопки',
            },
        ),
        migrations.CreateModel(
            name='TradeInSeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название серии')),
                ('start_cost', models.IntegerField(verbose_name='Начальная цена')),
                ('max_step', models.IntegerField(verbose_name='Всего шагов')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='TradeInStepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10, verbose_name='Номер шага')),
                ('name', models.CharField(max_length=60, verbose_name='Название шага')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_in.tradeinseriesmodel', verbose_name='Шаг для')),
            ],
            options={
                'verbose_name': 'Шаги',
                'verbose_name_plural': 'Шаги',
            },
        ),
        migrations.CreateModel(
            name='VariableFoeStepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название выбора')),
                ('increase', models.IntegerField(verbose_name='Увеличение при выборе на')),
                ('decrease', models.IntegerField(verbose_name='Уменьшение при выборе на')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_in.tradeinstepmodel', verbose_name='Номер шага')),
            ],
            options={
                'verbose_name': 'Выбор',
                'verbose_name_plural': 'Выбор',
            },
        ),
        migrations.CreateModel(
            name='UserStepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_ok', models.CharField(max_length=2, verbose_name='Текущий шаг')),
                ('cost', models.IntegerField(default=0, verbose_name='Текущая оценка')),
                ('device', models.CharField(max_length=50, verbose_name='Текущее устройство')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_in.telegramusermodel', verbose_name='Пользователь')),
            ],
        ),
    ]
