# Generated by Django 3.2.12 on 2022-06-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusermodel',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramusermodel',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Ник пользователя'),
        ),
    ]
