# Generated by Django 3.2.12 on 2022-04-30 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerproduct',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tune_admin.kitmodel', verbose_name='Комплект'),
        ),
    ]
