# Generated by Django 3.2.12 on 2022-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerproduct',
            name='device_provider',
            field=models.BooleanField(default=True),
        ),
    ]
