# Generated by Django 3.2.12 on 2022-05-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0004_alter_product_guaranty'),
        ('provider', '0005_alter_providerproduct_guaranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerproduct',
            name='guaranty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tune_admin.guarantymodel', verbose_name='Гарантия'),
        ),
    ]
