# Generated by Django 3.2.12 on 2022-04-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0002_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='device_provider',
            field=models.BooleanField(default=False, verbose_name='Устройство поставщика'),
        ),
    ]
