# Generated by Django 3.2.12 on 2022-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0003_product_device_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='www',
            field=models.BooleanField(default=True, verbose_name='Первичное SMT'),
        ),
    ]
