# Generated by Django 3.2.12 on 2022-05-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0004_alter_product_guaranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticUserHourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='ID пользователя ')),
                ('date_created', models.CharField(max_length=50, verbose_name='Дата сохдания')),
                ('hour_created', models.SmallIntegerField(verbose_name='Час создания')),
                ('full_id', models.CharField(max_length=50, verbose_name='час + ID')),
            ],
            options={
                'verbose_name': 'Юзер/час',
                'verbose_name_plural': 'Юзер/час',
            },
        ),
    ]
