# Generated by Django 3.2.12 on 2022-05-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0009_auto_20220523_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='sell_telergram',
            field=models.BooleanField(default=False, verbose_name='Продано в телеграмм?'),
        ),
    ]
