# Generated by Django 3.2.12 on 2022-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0010_bookingproduct_sell_telergram'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='date_sell',
            field=models.CharField(max_length=15, null=True, verbose_name='Дата продажи'),
        ),
    ]
