# Generated by Django 3.2.12 on 2022-06-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0013_product_discount_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGlobalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст для рассылки')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления'),
        ),
    ]
