# Generated by Django 3.2.12 on 2022-06-14 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0014_auto_20220614_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='region_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tune_admin.regionusermodel', verbose_name='Регион'),
        ),
    ]
