# Generated by Django 3.2.12 on 2022-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0015_alter_usermodel_region_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="\n                      Допустимые форматы:\n<br><br>\n                      -- iPhone 13 Pro 128 Silver\n<br>\n                      -- iPad mini 6 WiFi Silver\n<br>\n                      -- Watch 7 45 Silver\n<br>\n                      -- AirPods 3\n<br>\n                      -- MacBook Pro 13\n<br>\n                      -- MacBook / iMac 2021 24' 8/256", max_length=150, verbose_name='Название'),
        ),
    ]
