# Generated by Django 3.2.12 on 2022-06-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_admin', '0018_alter_sendglobalmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='provider_notifications',
            field=models.BooleanField(default=False, verbose_name='Уведомления постов поставщтка'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='service_notifications',
            field=models.BooleanField(default=False, verbose_name='Технические уведомления'),
        ),
    ]
