# Generated by Django 3.2.12 on 2022-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='image_1',
            field=models.ImageField(upload_to='trade', verbose_name='Картинка 1'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='image_2',
            field=models.ImageField(upload_to='trade', verbose_name='Картинка 2'),
        ),
    ]
