# Generated by Django 3.2.12 on 2022-05-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_in', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_button', models.CharField(max_length=255, verbose_name='Имена кнопок')),
            ],
            options={
                'verbose_name': 'Имена кнопок',
                'verbose_name_plural': 'Имена кнопок',
            },
        ),
        migrations.CreateModel(
            name='UserChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100, verbose_name='Устройство для ремонта')),
                ('cost', models.SmallIntegerField(verbose_name='Общаяя цена')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_in.telegramusermodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательские выборы',
            },
        ),
        migrations.CreateModel(
            name='UseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_id.userchoicemodel', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('time_process', models.SmallIntegerField(verbose_name='Время исполнения')),
                ('cost', models.IntegerField(verbose_name='Цена за услугу')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_id.buttonmodel', verbose_name='Услуга для')),
            ],
            options={
                'verbose_name': 'Услуга по ремонту',
                'verbose_name_plural': 'Услуги по ремонту',
            },
        ),
    ]
