# Generated by Django 3.2.12 on 2022-06-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('csv_id', models.CharField(max_length=50, verbose_name='Tilda ID')),
                ('cost', models.SmallIntegerField(verbose_name='Цена товара')),
                ('count', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Управление CSV',
                'verbose_name_plural': 'Управление CSV',
            },
        ),
    ]
