# Generated by Django 3.2.12 on 2022-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_models', '0002_csvmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='cost',
            field=models.IntegerField(verbose_name='Цена товара'),
        ),
    ]
